import { ModuleId } from "./modules";

export type FieldType = "number" | "text" | "checkbox" | "textarea" | "time" | "select";

export interface FieldDef {
  key: string;
  label: string;
  type: FieldType;
  default: number | string | boolean;
  min?: number;
  max?: number;
  step?: number;
  rows?: number;
  options?: { value: string; label: string }[];
  help?: string;
}

export interface ModuleConfigSchema {
  storageKey: string;
  fields: FieldDef[];
}

export type ModuleConfigSchemas = Partial<Record<ModuleId, ModuleConfigSchema>>;

export const MODULE_CONFIG_SCHEMAS: ModuleConfigSchemas = {
  auto_mint: {
    storageKey: "tw_suite_cfg_auto_mint",
    fields: [
      {
        key: "interval",
        label: "Check interval (ms)",
        type: "number",
        default: 90000,
        min: 10000,
        max: 600000,
        step: 1000,
        help: "How often to attempt minting coins.",
      },
      {
        key: "mintClickDelay",
        label: "Mint click delay (ms)",
        type: "number",
        default: 500,
        min: 100,
        max: 5000,
        step: 100,
      },
      {
        key: "refreshOnMissingAfterMs",
        label: "Refresh if mint missing (ms)",
        type: "number",
        default: 30000,
        min: 5000,
        max: 300000,
        step: 1000,
        help: "If the mint button is absent for this long, reload the page.",
      },
      {
        key: "minRefreshGapMs",
        label: "Min refresh gap (ms)",
        type: "number",
        default: 60000,
        min: 10000,
        max: 600000,
        step: 1000,
        help: "Minimum time between page reloads.",
      },
    ],
  },

  fakes: {
    storageKey: "tw_suite_cfg_fakes",
    fields: [
      {
        key: "attackDelay",
        label: "Attack delay (ms)",
        type: "number",
        default: 3500,
        min: 500,
        max: 30000,
        step: 100,
      },
      {
        key: "attackRandom",
        label: "Attack random ± (ms)",
        type: "number",
        default: 2500,
        min: 0,
        max: 10000,
        step: 100,
      },
      {
        key: "confirmDelay",
        label: "Confirm delay (ms)",
        type: "number",
        default: 800,
        min: 100,
        max: 10000,
        step: 100,
      },
      {
        key: "confirmRandom",
        label: "Confirm random ± (ms)",
        type: "number",
        default: 800,
        min: 0,
        max: 5000,
        step: 100,
      },
      {
        key: "switchDelay",
        label: "Village switch delay (ms)",
        type: "number",
        default: 8500,
        min: 1000,
        max: 60000,
        step: 500,
      },
      {
        key: "switchRandom",
        label: "Switch random ± (ms)",
        type: "number",
        default: 3500,
        min: 0,
        max: 20000,
        step: 500,
      },
      {
        key: "fakesPerVillage",
        label: "Max fakes per village (per run)",
        type: "number",
        default: 10,
        min: 1,
        max: 200,
        step: 1,
      },
      {
        key: "maxAttacksPerCoord",
        label: "Max attacks per coord",
        type: "number",
        default: 2,
        min: 1,
        max: 20,
        step: 1,
      },
      {
        key: "multiHitAttacks",
        label: "N attacks for lucky coords",
        type: "number",
        default: 2,
        min: 1,
        max: 10,
        step: 1,
      },
      {
        key: "multiHitChance",
        label: "Lucky coord chance (%)",
        type: "number",
        default: 20,
        min: 0,
        max: 100,
        step: 1,
      },
      {
        key: "arrivalStart",
        label: "Arrival window start",
        type: "time",
        default: "08:01",
      },
      {
        key: "arrivalEnd",
        label: "Arrival window end",
        type: "time",
        default: "22:58",
      },
      {
        key: "stopAtEnd",
        label: "Stop when all coords used",
        type: "checkbox",
        default: true,
      },
      {
        key: "maxCatapults",
        label: "Max catapults (caps rams)",
        type: "number",
        default: 1,
        min: 0,
        max: 50,
        step: 1,
      },
      {
        key: "maxScouts",
        label: "Max scouts",
        type: "number",
        default: 20,
        min: 0,
        max: 200,
        step: 1,
      },
      {
        key: "maxInfantry",
        label: "Max infantry",
        type: "number",
        default: 35,
        min: 0,
        max: 500,
        step: 1,
      },
      {
        key: "maxCavalry",
        label: "Max cavalry",
        type: "number",
        default: 999,
        min: 0,
        max: 999,
        step: 1,
      },
      {
        key: "coords",
        label: "Target coords",
        type: "textarea",
        default: "",
        rows: 5,
        help: "Space or newline-separated coords (format: 123|456).",
      },
    ],
  },

  mano_de_deus: {
    storageKey: "tw_suite_cfg_mano_de_deus",
    fields: [
      {
        key: "fineOffsetMs",
        label: "Fine offset (ms)",
        type: "number",
        default: 250,
        min: -5000,
        max: 5000,
        step: 1,
        help: "Positive = click later; negative = click earlier.",
      },
      {
        key: "alertLeadMs",
        label: "Alert lead time (ms)",
        type: "number",
        default: 10000,
        min: 0,
        max: 60000,
        step: 500,
        help: "How many ms before target to fire alerts.",
      },
      {
        key: "alertSoundEnabled",
        label: "Alert sound",
        type: "checkbox",
        default: true,
      },
      {
        key: "alertFlashEnabled",
        label: "Alert tab flash",
        type: "checkbox",
        default: true,
      },
      {
        key: "alertNotifyEnabled",
        label: "Desktop notification",
        type: "checkbox",
        default: true,
      },
    ],
  },

  noble_sender_trainer: {
    storageKey: "tw_suite_cfg_noble_sender",
    fields: [
      {
        key: "requestedNobles",
        label: "Default nobles to recruit",
        type: "number",
        default: 1,
        min: 1,
        max: 20,
        step: 1,
      },
      {
        key: "ignoreBelowPoints",
        label: "Ignore villages below (points)",
        type: "number",
        default: 1500,
        min: 0,
        max: 100000,
        step: 100,
      },
    ],
  },

  resource_buyer: {
    storageKey: "tw_suite_cfg_resource_buyer",
    fields: [
      {
        key: "PURCHASE_PERCENTAGE",
        label: "Target % of storage",
        type: "number",
        default: 70,
        min: 1,
        max: 100,
        step: 1,
        help: "Buy until each enabled resource is at this % of warehouse capacity.",
      },
      {
        key: "MAX_PREMIUM_POINTS",
        label: "Max premium points guard",
        type: "number",
        default: 300,
        min: 0,
        max: 10000,
        step: 10,
        help: "Pause buying when PP exceeds this threshold.",
      },
      {
        key: "PREMIUM_POINTS_TIMEOUT_MIN",
        label: "PP timeout (minutes)",
        type: "number",
        default: 10,
        min: 1,
        max: 120,
        step: 1,
      },
      {
        key: "MIN_STOCK_THRESHOLD",
        label: "Min exchange stock",
        type: "number",
        default: 50,
        min: 0,
        max: 100000,
        step: 50,
      },
      {
        key: "buy_wood",
        label: "Buy wood",
        type: "checkbox",
        default: true,
      },
      {
        key: "buy_stone",
        label: "Buy clay/stone",
        type: "checkbox",
        default: true,
      },
      {
        key: "buy_iron",
        label: "Buy iron",
        type: "checkbox",
        default: true,
      },
    ],
  },

  wh_balancer: {
    storageKey: "tw_suite_cfg_wh_balancer",
    fields: [
      {
        key: "highPoints",
        label: "Finished village threshold (points)",
        type: "number",
        default: 7000,
        min: 0,
        max: 100000,
        step: 100,
        help: "Villages above this point count are treated as 'built-out'.",
      },
      {
        key: "highFarm",
        label: "High farm threshold (population)",
        type: "number",
        default: 23000,
        min: 0,
        max: 30000,
        step: 100,
      },
      {
        key: "lowPoints",
        label: "Priority village threshold (points)",
        type: "number",
        default: 3000,
        min: 0,
        max: 50000,
        step: 100,
        help: "Villages below this are prioritised and filled to needsMorePercentage.",
      },
      {
        key: "builtOutPercentage",
        label: "Keep % for finished villages",
        type: "number",
        default: 0.26,
        min: 0.1,
        max: 0.95,
        step: 0.01,
      },
      {
        key: "needsMorePercentage",
        label: "Target % for priority villages",
        type: "number",
        default: 0.7,
        min: 0.1,
        max: 0.95,
        step: 0.01,
      },
      {
        key: "premiumInstantEnabled",
        label: "Enable instant trade (10pp)",
        type: "checkbox",
        default: false,
      },
      {
        key: "premiumThreshold",
        label: "PP trade threshold",
        type: "number",
        default: 50000,
        min: 0,
        max: 1000000,
        step: 1000,
      },
      {
        key: "premiumMoveAmount",
        label: "PP max move amount",
        type: "number",
        default: 300000,
        min: 0,
        max: 2000000,
        step: 10000,
      },
      {
        key: "premiumMaxDistance",
        label: "PP max donor distance",
        type: "number",
        default: 18,
        min: 1,
        max: 200,
        step: 1,
      },
      {
        key: "sendAllIntervalMs",
        label: "Send-all interval (ms)",
        type: "number",
        default: 500,
        min: 100,
        max: 10000,
        step: 100,
      },
    ],
  },

  mass_label_delay: {
    storageKey: "tw_suite_cfg_mass_label",
    fields: [
      {
        key: "minDelaySeconds",
        label: "Minimum delay (seconds)",
        type: "number",
        default: 120,
        min: 10,
        max: 600,
        step: 10,
        help: "Wait at least this many seconds before labelling.",
      },
      {
        key: "randomExtraMax",
        label: "Random extra max (seconds)",
        type: "number",
        default: 30,
        min: 0,
        max: 300,
        step: 5,
        help: "Add a random 0–N extra seconds on top of minimum delay.",
      },
      {
        key: "labelIndex",
        label: "Label radio index (0-based)",
        type: "number",
        default: 0,
        min: 0,
        max: 9,
        step: 1,
        help: "Which label option to select (0 = first).",
      },
    ],
  },

  tw_snipe_scheduler: {
    storageKey: "tw_suite_cfg_snipe_scheduler",
    fields: [
      {
        key: "gameSpeed",
        label: "Game speed",
        type: "number",
        default: 1.4,
        min: 0.1,
        max: 10,
        step: 0.01,
      },
      {
        key: "unitSpeed",
        label: "Unit speed",
        type: "number",
        default: 0.75,
        min: 0.1,
        max: 5,
        step: 0.01,
      },
    ],
  },
};
